--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.80.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04.10.2018 10:27:33
-- Server version: 8.0.12
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO contact_list.attachments(attachment_id, contact_id, attachment_filename, attachment_comment, attachment_date, deleted) VALUES
(1, 113, 'barash.jpg', 'fghfghfh', '2018-10-02', NULL),
(2, 114, 'dog.jpg', 'рапр', '2018-10-02', NULL),
(3, 0, 'dog.jpg', '', '2018-10-02', 1),
(4, 0, 'dog.jpg', '', '2018-10-02', 1),
(5, 116, 'barash.jpg', '', '2018-10-02', 1),
(6, 117, 'barash.jpg', '', '2018-10-02', NULL),
(7, 118, 'dog.jpg', '', '2018-10-02', NULL),
(8, 119, 'dog.jpg', '', '2018-10-02', NULL),
(9, 2, 'barash.jpg', '', '2018-10-03', 1),
(10, 2, 'barash.jpg', '', '2018-10-03', 1),
(11, 2, 'barash.jpg', '', '2018-10-03', NULL);