--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.80.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04.10.2018 10:27:35
-- Server version: 8.0.12
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO contact_list.contacts(contact_id, first_name, last_name, middle_name, birth_date, sex, citizenship, family_status, web_site, email, job, country, city, address, zip_code, deleted, avatar) VALUES
(1, 'Дмитрий', 'Липгарт', 'Вячеславович', '1988-10-04', 'male', 'ппа', 'married', 'аыаывавыаыв', 'dmitriylipgart@tut.by', 'dgfdgfdgf', 'рапрпрправ', 'Гомель', 'проспект Речицкий', '246023', NULL, 'barash.jpg'),
(2, 'Ivan', 'ivanov', 'ivanovich', '1990-10-04', 'male', 'rb', 'single', 'mail.com', 'dmitriylipgart@gmail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, '123.jpg'),
(3, 'Ivan', 'ivanov', 'ivanovich', '1990-10-03', 'male', 'rb', 'single', 'mail.com', 'sv4@modum.by', 'googlee', 'Belarus', 'Gomel', 'Kulman, 10', '123456', NULL, '123.jpg'),
(4, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'google', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(5, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(6, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(7, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', 1, NULL),
(8, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(9, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', 1, NULL),
(10, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', 1, NULL),
(11, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(12, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(13, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(14, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(15, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(16, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(17, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(18, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(19, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(20, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(21, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(22, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(23, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(24, 'Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL, NULL),
(25, 'Петр', 'Петров', 'Петрович', '1970-01-01', 'male', 'Беларусь', 'married', '', 'petrovich@mail.ru', 'ЗИП', 'Беларусь', 'Минск', 'Советская, 97-98', '2460000', NULL, NULL),
(26, 'Петр', 'Петров', 'Петрович', '2018-09-15', 'male', 'Беларусь', 'married', 'mail.com', 'petrovich@tut.by', 'Газпром', 'Беларусь', 'Гомель', 'Советская, 97-98', '246000', NULL, NULL),
(27, 'Петр', 'Петров', 'Петрович', '2018-09-15', 'male', 'Беларусь', 'married', 'mail.com', 'petrovich@tut.by', 'Газпром', 'Беларусь', 'Гомель', 'Советская, 97-98', '246000', NULL, NULL),
(28, 'Петр', 'Петров', 'Петрович', '2018-09-15', 'male', 'Беларусь', 'married', 'mail.com', 'petrovich@tut.by', 'Газпром', 'Беларусь', 'Гомель', 'Советская, 97-98', '246000', NULL, NULL),
(29, 'Петр', 'Петров', 'Петрович', '2018-09-15', 'male', 'Беларусь', 'married', 'mail.com', 'petrovich@tut.by', 'Газпром', 'Беларусь', 'Гомель', 'Советская, 97-98', '246000', NULL, NULL),
(30, 'Петр', 'Петров', 'Петрович', '2018-09-15', 'male', 'Беларусь', 'married', 'mail.com', 'petrovich@tut.by', 'Газпром', 'Беларусь', 'Гомель', 'Советская, 97-98', '246000', NULL, NULL),
(31, 'Петр', 'Петров', 'Петрович', '2018-09-15', 'male', 'Беларусь', 'married', 'mail.com', 'petrovich@tut.by', 'Газпром', 'Беларусь', 'Гомель', 'Советская, 97-98', '246000', NULL, NULL),
(32, 'John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', NULL, NULL),
(33, 'John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', NULL, NULL),
(34, 'John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street', '45000', NULL, NULL),
(35, 'John', 'Smith', '', '4444-04-04', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Гомель', 'проспект Речицкий', '246023', NULL, NULL),
(36, 'Петр', 'Петров', 'Петрович', '2222-02-22', 'male', 'Беларусь', 'married', 'mail.com', 'dmitriylipgart@tut.by', 'google', 'Беларусь', 'Гомель', 'проспект Речицкий', '246023', NULL, NULL),
(37, 'Дмитрий', 'Петров', 'Петрович', '3333-03-31', 'male', 'Беларусь', 'married', 'mail.com', 'dmitriylipgart@tut.by', 'google', 'USA', 'Гомель', 'проспект Речицкий', '246023', NULL, NULL),
(38, 'Петр', 'Петров', 'Петрович', '2222-02-22', 'male', 'Беларусь', 'married', 'mail.com', 'petrovich@mail.ru', 'google', 'USA', 'Palo-Alto', 'Palm Street', '4444444', NULL, NULL),
(39, 'Дмитрий', 'Липгарт', 'Вячеславович', '0333-03-31', 'male', 'USA', 'married', 'mail.com', 'dmitriylipgart@tut.by', 'google', 'USA', 'Гомель', 'проспект Речицкий', '246023', NULL, NULL);