SET NAMES 'utf8';
INSERT INTO contact_list.contacts(first_name, last_name, middle_name, birth_date, sex, citizenship, family_status, web_site, email, job, country, city, address, zip_code, deleted) VALUES
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', NULL),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', 1),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street', '45000', NULL),
('John', 'Smith', '', '4444-04-04', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Гомель', 'проспект Речицкий', '246023', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
  ('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', NULL),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', 1),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street', '45000', NULL),
  ('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', NULL),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', 1),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street', '45000', NULL),
  ('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', NULL),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street, 24', '450000', 1),
('John', 'Smith', '', '1990-01-01', 'male', 'USA', 'married', 'mail.com', 'john@mail.com', 'google', 'USA', 'Palo-Alto', 'Palm Street', '45000', NULL),
  ('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL),
('Ivan', 'ivanov', 'ivanovich', '1990-01-01', 'male', 'rb', 'single', 'mail.com', 'ivanov@mail.com', 'tuneyadec', 'Belarus', 'Minsk', 'Kulman, 10', '123456', NULL);
